include:
  - influx/docker-compose.influxdb.yaml
  - mosquitto/docker-compose.mosquitto.yaml
  - grafana/docker-compose.grafana.yaml

services:
  mqtt-to-influxdb:
    depends_on:
      - influxdb
      - mosquitto
    image: mqtt-to-influxdb
    build: .
    networks:
      - main
    environment:
      - RUN_ENV=DEFAULT

networks:
  main: