services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - main
    env_file:
      - path: .env
        required: true
    volumes:
      - ./influxdb/data:/var/lib/influxdb

networks:
  main:
