version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    # volumes:
    #   - ./influxdb/data:/var/lib/influxdb
    #   - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    #   - ./influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DB=defaultdb