services:
  mosquitto:
    build:
      context: .
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - main
    volumes:
      - ./mosquitto.log:/mosquitto/log/mosquitto.log:rw
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./passwd:/etc/mosquitto/passwd:rw

networks:
  main:
