version: "3"

services:
  eclipse-mosquitto:
    build:
      context: .
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto.log:/mosquitto/log/mosquitto.log:rw
      - ./passwd:/etc/mosquitto/passwd
